### ISSUE TITLE
get_key_filename does not fail if local target file cannot be created

### ISSUE THREAD

**Issue by osklil** [pfig/net-amazon-s3#12]
It seems get_key_filename in Net::Amazon::S3::Bucket (0.56) does not return failure if the local target file cannot be created. Try to download a file to a non-existant folder, e.g.

  $bucket->get_key_filename('some-existing-s3-file', 'GET', '/non-existant-dir/file')

and you will not get a failure.
I have only tried the 0.56 version and not the on in Github.
Let me know if I should do more testing or something else.

Regards,

Oskar Liljeblad (oskar@osk.mine.nu)

**Comment by thrig** [comment]
Hmm, this is actually a LWP behavior, as this module is just calling that:

    #!/usr/bin/env perl
    use strict;
    use warnings;
    
    use HTTP::Request;
    use LWP::UserAgent::Determined;
    
    my $req = HTTP::Request->new( GET => 'file:///etc/passwd' );
    my $ua = LWP::UserAgent->new;
    
    my $response = $ua->request( $req, '/nope/not/here' );
    print "ok\n" if $response->is_success;

**Comment by oalders** [comment]
Maybe check the response headers for Client-Aborted?

```
"Content-Length: 5253
Content-Type: text/plain
Last-Modified: Tue, 18 Feb 2014 05:43:39 GMT
Client-Aborted: die
Client-Date: Wed, 14 Jan 2015 20:39:50 GMT
X-Died: Can't write to '/nope/not/here': No such file or directory at /System/Library/Perl/Extras/5.18/LWP/Protocol.pm line 105.
"
```

**Comment by thrig** [comment]
https://github.com/libwww-perl/libwww-perl/pull/68 will hopefully better document this.

**Comment by pfig** [comment]
Hi,

Please update to 0.80 and if this still persists please open an issue in @rustyconover's fork, https://github.com/rustyconover/net-amazon-s3.
