### ISSUE TITLE
bucket->list fails on objects uploaded with the multipart upload API

### ISSUE THREAD

**Issue by jjschutz2** [pfig/net-amazon-s3#15]
Objects uploaded with the multipart upload API are given an ETag which is not a 32-character MD5 hash, e.g. of the form 010296dfa0b2b83267959dfbafa3db64-1 (AWS docs say these can "contain one or more non-hexadecimal characters and/or will consist of less than 32 or more than 32 hexadecimal digits."), causing type checking to fail on the ETag type in the Object constructor.

Sample code to list a bucket:

    my @keys;
    my $stream = $bucket->list( { prefix => $key } );
    until ( $stream->is_done ) {
        foreach my $object ( $stream->items ) {
            push(@keys, $object->key);
        }
    }

Resulting backtrace:

Attribute (etag) does not pass the type constraint because: Validation failed for 'Etag' with value 010296dfa0b2b83267959dfbafa3db64-1 at constructor Net::Amazon::S3::Client::Object::new (defined at /usr/local/share/perl5/Net/Amazon/S3/Client/Object.pm line 50) line 93
        Net::Amazon::S3::Client::Object::new('Net::Amazon::S3::Client::Object', 'client', 'Net::Amazon::S3::Client=HASH(0x3cfce70)', 'bucket', 'Net::Amazon::S3::Client::Bucket=HASH(0x45f4628)', 'key', 'logs/trace/2012/20121214.log', 'last_modified', '2012-12-14T00:06:07.000Z', 'etag', '010296dfa0b2b83267959dfbafa3db64-1', 'size', 3068402) called at /usr/local/share/perl5/Net/Amazon/S3/Client/Bucket.pm line 109
        Net::Amazon::S3::Client::Bucket::__ANON__('Data::Stream::Bulk::Callback=HASH(0x3ef3fc8)') called at /usr/local/share/perl5/Data/Stream/Bulk/Callback.pm line 25
        Data::Stream::Bulk::Callback::get_more('Data::Stream::Bulk::Callback=HASH(0x3ef3fc8)') called at /usr/local/share/perl5/Data/Stream/Bulk/DoneFlag.pm line 37
        Data::Stream::Bulk::DoneFlag::next('Data::Stream::Bulk::Callback=HASH(0x3ef3fc8)') called at /usr/local/share/perl5/Data/Stream/Bulk.pm line 18
        Data::Stream::Bulk::items('Data::Stream::Bulk::Callback=HASH(0x3ef3fc8)') 

-- 
Jon Schutz
CTO, YourAmigo Ltd
53 Gilbert St
Adelaide SA 5000
Ph:  +61 8 82119211
Fax: +61 8 8211 6356
http://www.youramigo.com

**Comment by pfig** [comment]
Hi,

Please update to 0.80 and if this still persists please open an issue in @rustyconover's fork, https://github.com/rustyconover/net-amazon-s3.
