### ISSUE TITLE
GETBucketWebsite, PUTBucketWebsite, DELETEBucketWebSite

### ISSUE THREAD

**Issue by JamesBromberger** [pfig/net-amazon-s3#16]
Want to be able to get the current website configuration for an S3 bucket, and also set it and delete it. As per documentation:

http://docs.amazonwebservices.com/AmazonS3/latest/API/RESTBucketGETwebsite.html
http://docs.amazonwebservices.com/AmazonS3/latest/API/RESTBucketDELETEwebsite.html
http://docs.amazonwebservices.com/AmazonS3/latest/API/RESTBucketPUTwebsite.html

**Comment by pfig** [comment]
Hi,

Please update to 0.80 and if this still persists please open an issue in @rustyconover's fork, https://github.com/rustyconover/net-amazon-s3.
