### ISSUE TITLE
Add support for server-side encryption in Net::Amazon::S3::Client::Object

### ISSUE THREAD

**Issue by ehammond** [pfig/net-amazon-s3#2]
I would like to be able to request server-side encryption for some new objects I upload to S3.

This can be done by specifying the following header:

 x-amz-server-side-encryption: AES256

Reference:

  http://docs.amazonwebservices.com/AmazonS3/latest/dev/index.html?SSEUsingRESTAPI.html

**Comment by pfig** [comment]
Hi,

Please update to 0.80 and if this still persists please open an issue in @rustyconover's fork, https://github.com/rustyconover/net-amazon-s3.
