### ISSUE TITLE
Net::Amazon::S3::HTTPRequest doesn't support ScalarRef content property

### ISSUE THREAD

**Issue by struanb** [pfig/net-amazon-s3#20]
Net::Amazon::S3::HTTPRequest (and classes that use it) don't support ScalarRef content property for passing a scalar ref $content to HTTP::Request. This makes using Net::Amazon::S3 with large amount of content extremely memory inefficient. Since content must currently be passed in as a scalar; each time the scalar is copied, process memory usage multiplies. The following patch trivially fixes this in HTTPRequest.pm. Classes using HTTPRequest such as PutObject would benefit from similar treatment, although it would seem methods like PutObject::put would require modification to ensure the md5 is correctly calculated from the dereferenced scalar ref.

<pre>
diff -rubw lib/Net/Amazon/S3/HTTPRequest.pm /usr/share/perl5/Net/Amazon/S3/HTTPRequest.pm
--- lib/Net/Amazon/S3/HTTPRequest.pm	2013-03-16 09:43:31.000000000 +0000
+++ /usr/share/perl5/Net/Amazon/S3/HTTPRequest.pm	2013-03-28 00:19:28.000000000 +0000
@@ -24,7 +24,7 @@
 has 'headers' =>
     ( is => 'ro', isa => 'HashRef', required => 0, default => sub { {} } );
 has 'content' =>
-    ( is => 'ro', isa => 'Str|CodeRef', required => 0, default => '' );
+    ( is => 'ro', isa => 'Str|CodeRef|ScalarRef', required => 0, default => '' );
 has 'metadata' =>
</pre>

**Comment by pfig** [comment]
Hi,

Please update to 0.80 and if this still persists please open an issue in @rustyconover's fork, https://github.com/rustyconover/net-amazon-s3.
