### ISSUE TITLE
Install Issue

### ISSUE THREAD

**Issue by elmic11111** [pfig/net-amazon-s3#30]
#   Failed test 'Net::Amazon::S3::Request::PutPart loaded ok'
#   at t/00-compile.t line 62.
#                   ''
#     doesn't match '(?s-xim:^\s*Net::Amazon::S3::Request::PutPart ok)'
t/00-compile.................ok 24/25
#   Failed test 's3cl script compiles'
#   at t/00-compile.t line 70.
# 9 - Possible unintended interpolation of @pedrofigueiredo in string at /root/.cpan/build/Net-Amazon-S3-0.59/blib/lib/Net/Amazon/S3/Request/PutPart.pm line 44.
# Bareword found where operator expected at /root/.cpan/build/Net-Amazon-S3-0.59/blib/lib/Net/Amazon/S3/Request/PutPart.pm line 93, near "This is free software; you can redistribute it and/or"
#   (Might be a runaway multi-line // string starting on line 44)
# Global symbol "$http_request" requires explicit package name at /root/.cpan/build/Net-Amazon-S3-0.59/blib/lib/Net/Amazon/S3/Request/PutPart.pm line 44.
# Global symbol "$s3" requires explicit package name at /root/.cpan/build/Net-Amazon-S3-0.59/blib/lib/Net/Amazon/S3/Request/PutPart.pm line 44.
# Global symbol "$bucket" requires explicit package name at /root/.cpan/build/Net-Amazon-S3-0.59/blib/lib/Net/Amazon/S3/Request/PutPart.pm line 44.
# Global symbol "$key" requires explicit package name at /root/.cpan/build/Net-Amazon-S3-0.59/blib/lib/Net/Amazon/S3/Request/PutPart.pm line 44.
# Global symbol "$value" requires explicit package name at /root/.cpan/build/Net-Amazon-S3-0.59/blib/lib/Net/Amazon/S3/Request/PutPart.pm line 44.
# Global symbol "$acl_short" requires explicit package name at /root/.cpan/build/Net-Amazon-S3-0.59/blib/lib/Net/Amazon/S3/Request/PutPart.pm line 44.
# Global symbol "$conf" requires explicit package name at /root/.cpan/build/Net-Amazon-S3-0.59/blib/lib/Net/Amazon/S3/Request/PutPart.pm line 44.
# Global symbol "$part_number" requires explicit package name at /root/.cpan/build/Net-Amazon-S3-0.59/blib/lib/Net/Amazon/S3/Request/PutPart.pm line 44.
# Global symbol "$upload_id" requires explicit package name at /root/.cpan/build/Net-Amazon-S3-0.59/blib/lib/Net/Amazon/S3/Request/PutPart.pm line 44.
# Global symbol "@pedrofigueiredo" requires explicit package name at /root/.cpan/build/Net-Amazon-S3-0.59/blib/lib/Net/Amazon/S3/Request/PutPart.pm line 44.
# /root/.cpan/build/Net-Amazon-S3-0.59/blib/lib/Net/Amazon/S3/Request/PutPart.pm has too many errors.
# Compilation failed in require at /root/.cpan/build/Net-Amazon-S3-0.59/blib/lib/Net/Amazon/S3.pm line 34.
# BEGIN failed--compilation aborted at /root/.cpan/build/Net-Amazon-S3-0.59/blib/lib/Net/Amazon/S3.pm line 34.
# Compilation failed in require at bin/s3cl line 9.
# BEGIN failed--compilation aborted at bin/s3cl line 9.
# Looks like you failed 3 tests of 25.
t/00-compile.................dubious

**Comment by pfig** [comment]
Hi,

Please update to 0.80 and if this still persists please open an issue in @rustyconover's fork, https://github.com/rustyconover/net-amazon-s3.
