### ISSUE TITLE
multipart upload from file

### ISSUE THREAD

**Issue by vkatsikaros** [pfig/net-amazon-s3#34]
Hi

I am trying to figure out if it is possible for Net::Amazon::S3::Client::Object->put_part to handle a function for reading a file instead of actually passing the content to PUT.

Net::Amazon::S3::Client::Object->put_filename can do this so I was wondering if I can do this without writing my own code for reading the file.

**Comment by pfig** [comment]
Hi,

Please update to 0.80 and if this still persists please open an issue in @rustyconover's fork, https://github.com/rustyconover/net-amazon-s3.
