### ISSUE TITLE
content iterator not reset before retry

### ISSUE THREAD

**Issue by jdv** [pfig/net-amazon-s3#35]
Some of our processes started getting intermittent 500s on put_filename()
calls which is fine though its still not clear why only certain processes suffer
from this minor issue.

The problematic issue is that the subsequent retry is failing with a 400.
After further investigation it was discovered that these post 500 400s
are caused by the content iterator being midstream for the retry
request and therefore delivering partial content.  A hack we may employ
for the time being is to just exhaust the iterator before a retry since it will
then reset itself.  But a real fix would probably involve being able to reset
or replace the iterator before a retry.

**Comment by rustyconover** [comment]
@jdv: can you supply some example code to reproduce this error?

**Comment by pfig** [comment]
Hi,

Please update to 0.80 and if this still persists please open an issue in @rustyconover's fork, https://github.com/rustyconover/net-amazon-s3.
