### ISSUE TITLE
location_constraint => 'EU' fails for US users

### ISSUE THREAD

**Issue by jhannah** [pfig/net-amazon-s3#37]
Hello. I live in the US, and `t/02client.t` fails for me due to `location_constraint => 'EU'`
````
OperationAborted: A conflicting conditional operation is currently in progress against this resource. Please try again. at lib/Net/Amazon/S3/Client.pm line 98.
````
Shall I add an optional environmental variable US folks can set? Or remove the EU specification? (Does it not default to EU when running it from Europe?)

Thanks!

**Comment by pfig** [comment]
Hi,

Please update to 0.80 and if this still persists please open an issue in @rustyconover's fork, https://github.com/rustyconover/net-amazon-s3.
