### ISSUE TITLE
Passing a list of values to enum is deprecated

### ISSUE THREAD

**Issue by barbie** [pfig/net-amazon-s3#44]
Hi,

I think this report is related to your module:

http://www.cpantesters.org/cpan/report/13c61bd2-dc03-11e3-aa0f-deebe0bfc7aa

In particular this bit:

Passing a list of values to enum is deprecated. Enum values should be wrapped in an arrayref. at /usr/perl5.18.2/lib/site_perl/5.18.2/amd64-freebsd/Moose/Util/TypeConstraints.pm line 440.
	Moose::Util::TypeConstraints::enum("StorageClass", "standard", "reduced_redundancy") called at /usr/perl5.18.2/lib/site_perl/5.18.2/Net/Amazon/S3/Client/Object.pm line 21
	require Net/Amazon/S3/Client/Object.pm called at /usr/perl5.18.2/lib/site_perl/5.18.2/Net/Amazon/S3.pm line 17

Looking at line 21 it would seem you've missing some enclosing "[]".

Thanks,
Barbie.

**Comment by article7** [comment]
+1 also

**Comment by kizashi1122** [comment]
+1

**Comment by kizashi1122** [comment]
How do you guys workaround for this?

**Comment by kurmanka** [comment]
@kizashi1122 https://github.com/iinteractive/net-amazon-s3/commit/116d73235d8243ec4427e6d7bf1f14f7fb9129aa

**Comment by kizashi1122** [comment]
@kurmanka Thanks!

But `cpanm git@github.com:iinteractive/net-amazon-s3.git` doesn't work because of lack of Makafile.PL.

Did you fix installed module directly?

**Comment by yanick** [comment]
I've added a  dzil-processed version of that patch. You can install it directly from GitHub via

`cpanm git://github.com/iinteractive/net-amazon-s3.git@build/enum_patch`

Enjoy. :-)

**Comment by kizashi1122** [comment]
@yanick 
Thank you! It worked!

**Comment by yanick** [comment]
@kizashi1122  Excellent!

**Comment by akarelas** [comment]
Why won't the developer fix this? This is a really old bug.

**Comment by karenetheridge** [comment]
I'm willing to take comaint to get a new release out.

**Comment by rustyconover** [comment]
Hi Karen,

I’ve just go co-maint bits but Pedro said he was working on things, but since I emailed him last week I haven’t heard anything yet…  I’ll give it a few more days and release out of my tree.

Rusty

-- 
Rusty Conover
Lucky Dinosaur, LLC.

On April 11, 2015 at 8:59:43 PM, Karen Etheridge (notifications@github.com) wrote:

I'm willing to take comaint to get a new release out.

**Comment by karenetheridge** [comment]
I think this can be closed now, as the fix is in 0.80?

**Comment by rustyconover** [comment]
Yes indeed.
