### ISSUE TITLE
Parsing errors whilst streaming S3 list requests

### ISSUE THREAD

**Issue by lerlands** [pfig/net-amazon-s3#50]
I have a perl module for handling files stored under S3. The number of files can be in the order of a few tens of thousands of files in a bucket.

In order to list all the files matching a specific pattern (not done very often), I make use of  Net::Amazon::S3::Client::Bucket::list, and loops with $stream->is_done.

The code is:

sub store_list_images {
  my ( $self, $prefix, %attr ) = @_;
  my (@keys);

  $self->log_fatal("No S3 object instantiated") unless ( $self->_s3 );
  $self->log_fatal("No bucket specified") unless ( exists( $attr{bucket} ) && ( $attr{bucket} ) );

  my $bucket = $self->_s3->bucket( name => $attr{bucket} );
  my $stream;
  if ($prefix) {
    $stream = $bucket->list( { prefix => $prefix } );
  }
  else {
    $stream = $bucket->list;
  }
  until ( $stream->is_done ) {
    $self->log_debug( "Stream has been read" );
    foreach my $object ( $stream->items ) {
      push(@keys, $object->key);
    }
  }
  return wantarray ? @keys : \@keys;
}

Whilst running it, I get parsing errors:

[31/Jul/2014:11:34:45] New.Role.Logger DEBUG Logger.pm New::Role::Logger::log_debug 215 - Stream has been read
[31/Jul/2014:11:34:53] New.Role.Logger DEBUG Logger.pm New::Role::Logger::log_debug 215 - Stream has been read
[31/Jul/2014:11:35:06] New.Role.Logger DEBUG Logger.pm New::Role::Logger::log_debug 215 - Stream has been read
[31/Jul/2014:11:35:15] New.Role.Logger DEBUG Logger.pm New::Role::Logger::log_debug 215 - Stream has been read
[31/Jul/2014:11:35:25] New.Role.Logger DEBUG Logger.pm New::Role::Logger::log_debug 215 - Stream has been read
[31/Jul/2014:11:35:36] New.Role.Logger DEBUG Logger.pm New::Role::Logger::log_debug 215 - Stream has been read
[31/Jul/2014:11:35:45] New.Role.Logger DEBUG Logger.pm New::Role::Logger::log_debug 215 - Stream has been read
:2: parser error : expected '>'
ID><DisplayName>aws.admin</DisplayName></Owner><StorageClass>STANDARD</StorageCl
                                                                                ^
:2: parser error : Opening and ending tag mismatch: StorageClass line 2 and StorageCl
ID><DisplayName>aws.admin</DisplayName></Owner><StorageClass>STANDARD</StorageCl
                                                                                ^
:2: parser error : Premature end of data in tag Contents line 2
ID><DisplayName>aws.admin</DisplayName></Owner><StorageClass>STANDARD</StorageCl
                                                                                ^
:2: parser error : Premature end of data in tag ListBucketResult line 2
ID><DisplayName>aws.admin</DisplayName></Owner><StorageClass>STANDARD</StorageCl

I am available and very willing to run any special processing and dump any necessary data structures to help debugging the issue.

Version:

$Net::Amazon::S3::VERSION = '0.59';

Thanks,
Lars Erlandsen.

**Comment by pfig** [comment]
Hi,

Please update to 0.80 and if this still persists please open an issue in @rustyconover's fork, https://github.com/rustyconover/net-amazon-s3.
