### ISSUE TITLE
copy_key does not URL-encode the source path

### ISSUE THREAD

**Issue by tamias** [pfig/net-amazon-s3#51]
The source path for copy_key() is specified in the S3 request in the x-amz-copy-source header.  According to the documentation: "This string must be URL-encoded."  copy_key() does not URL-encode the source path, which results in a NoSuchKey error if the path contains percent or plus characters.

http://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectCOPY.html

**Comment by pfig** [comment]
Hi,

Please update to 0.80 and if this still persists please open an issue in @rustyconover's fork, https://github.com/rustyconover/net-amazon-s3.
