### ISSUE TITLE
Not able to specify API endpoint.

### ISSUE THREAD

**Issue by higgz** [pfig/net-amazon-s3#52]
While Amazon::S3 allows users to set $host to the endpoint they wish to use, the Net::Amazon::S3 module works only with the official Amazon API, preventing use of other providers (dreamhost, local ceph cluster via radosgw).

**Comment by pfig** [comment]
Hi,

Please update to 0.80 and if this still persists please open an issue in @rustyconover's fork, https://github.com/rustyconover/net-amazon-s3.
