### ISSUE TITLE
unauthorized modules in the last release (0.80)

### ISSUE THREAD

**Issue by karenetheridge** [pfig/net-amazon-s3#65]
https://metacpan.org/release/Net-Amazon-S3 shows the following modules did not
get indexed by RCONOVER:

Net::Amazon::S3::Request::CompleteMultipartUpload
Net::Amazon::S3::Request::DeleteMultiObject
Net::Amazon::S3::Request::InitiateMultipartUpload
Net::Amazon::S3::Request::ListParts
Net::Amazon::S3::Request::PutPart

**Comment by rustyconover** [comment]
That was the fault of the CPAN guys, I did eventually get granted co-maint on those namespaces.

Should I re-release?

Rusty
-- 
Rusty Conover
Lucky Dinosaur, LLC.

On May 4, 2015 at 7:07:46 PM, Karen Etheridge (notifications@github.com) wrote:

https://metacpan.org/release/Net-Amazon-S3 shows the following modules did not
get indexed by RCONOVER:

Net::Amazon::S3::Request::CompleteMultipartUpload
Net::Amazon::S3::Request::DeleteMultiObject
Net::Amazon::S3::Request::InitiateMultipartUpload
Net::Amazon::S3::Request::ListParts
Net::Amazon::S3::Request::PutPart

**Comment by karenetheridge** [comment]
I believe all you need to do is request that PAUSE reindex the distribution: https://pause.perl.org/pause/authenquery?ACTION=reindex

**Comment by rustyconover** [comment]
Thanks, and done.

Rusty

-- 
Rusty Conover
Lucky Dinosaur, LLC.

On May 4, 2015 at 8:41:32 PM, Karen Etheridge (notifications@github.com) wrote:

I believe all you need to do is request that PAUSE reindex the distribution: https://pause.perl.org/pause/authenquery?ACTION=reindex
