### ISSUE TITLE
"list" fails with files containing control characters

### ISSUE THREAD

**Issue by davel** [pfig/net-amazon-s3#67]
Somehow we have ended up with an S3 key containing character 8. This upsets XML parsing,

```
:2: parser error : xmlParseCharRef: invalid xmlChar value 8
Class>STANDARD</StorageClass></Contents><Contents><Key>xxx#x8;
                                                              ^
```

**Comment by pfig** [comment]
Hi,

Please update to 0.80 and if this still persists please open an issue in @rustyconover's fork, https://github.com/rustyconover/net-amazon-s3.
