### ISSUE TITLE
Support automatic following of redirection

### ISSUE THREAD

**Issue by ranguard** [pfig/net-amazon-s3#9]
Created a bucket in 'EU' - but when trying to save a PDF (using add_key_filename) to it get this back as the error:

TemporaryRedirectPlease re-send this request to the specified temporary endpoint. Continue to use the original request endpoint for future requests.

I can't create a test case for some reason - seems to work fine unfortunately!

**Comment by pfig** [comment]
Hi,

Please update to 0.80 and if this still persists please open an issue in @rustyconover's fork, https://github.com/rustyconover/net-amazon-s3.
